### ISSUE TITLE
Preview flickers on each preview

### ISSUE THREAD

**Issue by DinisCruz** [gruehle/MarkdownPreview#67]
Which is problematic since it distracts while writing

I'm on the latest versions of OSX and Brackets

**Comment by cfjedimaster** [comment]
+1 - this looks like the bug I opened too.

**Comment by DinisCruz** [comment]
@cfjedimaster if this is a duplicate of your one, just link it here and close this one :)

**Comment by cfjedimaster** [comment]
This was mine, https://github.com/gruehle/MarkdownPreview/issues/63.

**Comment by gruehle** [comment]
It looks like this was caused by the Chromium update in the latest brackets shell. The update was changed in 77f8aafb2d933907b28910e413e95efd07f556ae to reset just the body html instead of the entire frame. This fixes the problem for me on OSX and Win 8.1. Please let me know if you're still seeing the problem.

**Comment by cfjedimaster** [comment]
Thanks for fixing this!
